/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        "background": "#fff8f5",
        "on-tertiary": "#ffffff",
        "on-surface": "#1f1b18",
        "on-tertiary-fixed": "#1f1b15",
        "tertiary-fixed-dim": "#cec5bc",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb4a2",
        "surface-tint": "#8e4c3b",
        "secondary": "#855408",
        "tertiary-fixed": "#eae1d7",
        "on-surface-variant": "#53433f",
        "primary-container": "#d98a76",
        "on-primary-container": "#5b2517",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#784a00",
        "primary-fixed-dim": "#ffb4a2",
        "error-container": "#ffdad6",
        "inverse-surface": "#352f2c",
        "on-background": "#1f1b18",
        "tertiary-container": "#a59d94",
        "on-tertiary-container": "#39352e",
        "primary-fixed": "#ffdad2",
        "surface-bright": "#fff8f5",
        "surface": "#fff8f5",
        "on-primary-fixed-variant": "#713526",
        "tertiary": "#635d56",
        "on-secondary-fixed-variant": "#663e00",
        "outline-variant": "#d8c2bc",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#4b463f",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#faefe9",
        "surface-container-highest": "#ebe0db",
        "surface-dim": "#e2d8d3",
        "on-error": "#ffffff",
        "surface-container-low": "#fdf1ec",
        "surface-container-high": "#f1e6e1",
        "primary": "#8e4c3b",
        "on-primary-fixed": "#390b02",
        "secondary-fixed-dim": "#fcba69",
        "secondary-container": "#ffbc6c",
        "secondary-fixed": "#ffddb9",
        "on-secondary-fixed": "#2b1700",
        "outline": "#86736e",
        "surface-container": "#f7ece6",
        "surface-variant": "#ebe0db"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "body-md":              ["Manrope", "sans-serif"],
        "headline-lg":          ["EB Garamond", "serif"],
        "title-lg":             ["EB Garamond", "serif"],
        "editorial-quote":      ["EB Garamond", "serif"],
        "headline-md":          ["EB Garamond", "serif"],
        "body-sm":              ["Manrope", "sans-serif"],
        "label-md":             ["Manrope", "sans-serif"],
        "label-sm":             ["Manrope", "sans-serif"],
        "title-md":             ["Manrope", "sans-serif"],
        "display-lg":           ["EB Garamond", "serif"],
        "body-lg":              ["Manrope", "sans-serif"],
        "headline-sm":          ["EB Garamond", "serif"],
        "display-lg-mobile":    ["EB Garamond", "serif"],
        "headline-lg-mobile":   ["EB Garamond", "serif"]
      },
      fontSize: {
        "body-md":            ["15px",  { lineHeight: "24px",  letterSpacing: "0em",     fontWeight: "400" }],
        "headline-lg":        ["40px",  { lineHeight: "48px",  letterSpacing: "-0.015em", fontWeight: "400" }],
        "title-lg":           ["20px",  { lineHeight: "28px",  letterSpacing: "0em",     fontWeight: "500" }],
        "editorial-quote":    ["24px",  { lineHeight: "36px",  letterSpacing: "0.01em",  fontWeight: "400" }],
        "headline-md":        ["30px",  { lineHeight: "38px",  letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-sm":            ["13px",  { lineHeight: "20px",  letterSpacing: "0.005em", fontWeight: "400" }],
        "label-md":           ["12px",  { lineHeight: "16px",  letterSpacing: "0.08em",  fontWeight: "600" }],
        "label-sm":           ["11px",  { lineHeight: "14px",  letterSpacing: "0.1em",   fontWeight: "600" }],
        "title-md":           ["16px",  { lineHeight: "24px",  letterSpacing: "0.01em",  fontWeight: "600" }],
        "display-lg":         ["56px",  { lineHeight: "64px",  letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-lg":            ["18px",  { lineHeight: "28px",  letterSpacing: "-0.005em",fontWeight: "400" }],
        "headline-sm":        ["22px",  { lineHeight: "30px",  letterSpacing: "0em",     fontWeight: "500" }],
        "display-lg-mobile":  ["38px",  { lineHeight: "46px",  letterSpacing: "-0.015em",fontWeight: "400" }],
        "headline-lg-mobile": ["30px",  { lineHeight: "38px",  letterSpacing: "-0.01em", fontWeight: "400" }]
      },
      spacing: {
        "space-xl":          "2rem",
        "margin-mobile":     "1.25rem",
        "margin-desktop":    "3.5rem",
        "gutter-desktop":    "2rem",
        "space-4xl":         "6rem",
        "space-2xl":         "3rem",
        "space-xs":          "0.5rem",
        "space-sm":          "0.75rem",
        "space-3xl":         "4.5rem",
        "space-md":          "1rem",
        "gutter-mobile":     "1rem",
        "space-2xs":         "0.25rem",
        "space-lg":          "1.5rem"
      }
    }
  },
  plugins: [
    require("@tailwindcss/forms")
  ]
}
